# Generated by Django 3.0.1 on 2019-12-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cost', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=313)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
