# Generated by Django 3.0.1 on 2020-01-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20200104_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'ارسال ها', 'verbose_name_plural': 'ارسال ها'},
        ),
    ]
