# Generated by Django 5.2 on 2025-05-30 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.PositiveIntegerField(verbose_name='User Number')),
                ('product_number', models.PositiveIntegerField(verbose_name='Product Number')),
                ('massage_number', models.PositiveIntegerField(verbose_name='Massage Number')),
                ('new_order_number', models.PositiveIntegerField(verbose_name='Order Number')),
                ('ongoing_order_number', models.PositiveIntegerField(verbose_name='Ongoing Order Number')),
                ('ready_order_number', models.PositiveIntegerField(verbose_name='Ready Order Number')),
            ],
            options={
                'verbose_name': 'Counter Report',
                'verbose_name_plural': 'Counter Reports',
            },
        ),
        migrations.CreateModel(
            name='DailySaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_product_income', models.PositiveIntegerField(verbose_name='Total Product Income')),
                ('total_options_income', models.PositiveIntegerField(verbose_name='Total Option Income')),
                ('sale_counter', models.PositiveIntegerField(verbose_name='Sale Counter')),
                ('total_delivery_income', models.PositiveIntegerField(verbose_name='Total Delivery Income')),
                ('total_discount', models.PositiveIntegerField(verbose_name='Total Discount Sale')),
            ],
            options={
                'verbose_name': 'Daily Sale Report',
                'verbose_name_plural': 'Daily Sale Reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('total_product_income', models.PositiveIntegerField(verbose_name='Total Product Income')),
                ('total_options_income', models.PositiveIntegerField(verbose_name='Total Option Income')),
                ('sale_counter', models.PositiveIntegerField(verbose_name='Sale Counter')),
                ('total_delivery_income', models.PositiveIntegerField(verbose_name='Total Delivery Income')),
                ('total_discount', models.PositiveIntegerField(verbose_name='Total Discount Sale')),
            ],
            options={
                'verbose_name': 'Monthly Sale Report',
                'verbose_name_plural': 'Monthly Sale Reports',
                'ordering': ['-month', '-year'],
            },
        ),
    ]
