# Generated by Django 3.0.1 on 2020-01-06 08:52

import django.core.validators
from django.db import migrations, models
import interface.models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('background', models.ImageField(upload_to=interface.models.background_image_directory_path)),
                ('header', models.ImageField(upload_to=interface.models.header_image_directory_path)),
            ],
        ),
    ]
