# Generated by Django 3.0.1 on 2020-01-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_mainimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlidShow',
            new_name='SlideShow',
        ),
    ]
