# Generated by Django 3.0.1 on 2019-12-31 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('mobile', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Mobile Number')),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('confirm_code', models.CharField(max_length=4, null=True)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('Profile', models.ImageField(blank=True, default=0, upload_to='', verbose_name='Profile Image')),
                ('reg_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('IRI', 'ایران')], default='IRI', max_length=3)),
                ('state', models.CharField(choices=[('TEH', 'تهران')], default='TEH', max_length=3)),
                ('area', models.CharField(blank=True, max_length=25)),
                ('detail', models.CharField(max_length=313, verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='user.User')),
            ],
        ),
    ]
