# Generated by Django 3.0.1 on 2020-01-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile',
            field=models.ImageField(blank=True, upload_to='./img', verbose_name='Profile Image'),
        ),
    ]
