# Generated by Django 3.0.1 on 2019-12-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='area',
        ),
    ]
