# Generated by Django 3.0.1 on 2020-01-04 07:24

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200104_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile',
            field=models.ImageField(blank=True, upload_to=user.models.user_profile_directory_pass, verbose_name='Profile Image'),
        ),
    ]
