# Generated by Django 3.0.1 on 2020-01-04 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200104_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('mobile', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Mobile Number')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('confirm_code', models.CharField(max_length=4, null=True)),
                ('email', models.CharField(blank=True, max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('Profile', models.ImageField(blank=True, upload_to=user.models.user_profile_directory_pass, verbose_name='Profile Image')),
                ('reg_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='user.User'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
