# Generated by Django 3.0.1 on 2020-01-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200104_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Profile',
            new_name='profile',
        ),
    ]
