# Generated by Django 3.0.1 on 2020-01-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200104_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rule',
            field=models.CharField(choices=[('csm', 'مشتری'), ('col', 'همکار'), ('fde', 'طراح'), ('nde', 'طراح غیرحضوری'), ('man', 'مدیریت'), ('opr', 'اپراتور'), ('pre', 'مدیریت داخلی'), ('acc', 'حسابدار')], default='csm', max_length=3),
        ),
    ]
