# Generated by Django 3.0.1 on 2020-01-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200105_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_tg',
            name='rule',
        ),
        migrations.AddField(
            model_name='user_tg',
            name='role',
            field=models.CharField(choices=[('csm', 'مشتری'), ('col', 'همکار'), ('fde', 'طراح'), ('nde', 'طراح غیرحضوری'), ('man', 'مدیریت'), ('opr', 'اپراتور'), ('pre', 'مدیریت داخلی'), ('acc', 'حسابدار'), ('itm', 'مدیر سایت')], default='csm', max_length=3),
        ),
    ]
