# Generated by Django 3.0.1 on 2020-01-05 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_cartaction_orderaction'),
        ('user', '0013_auto_20200105_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_TG',
            new_name='UserTG',
        ),
    ]
