# Generated by Django 3.0.1 on 2020-01-07 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0015_auto_20200106_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertg',
            name='role',
            field=models.CharField(choices=[('csm', 'مشتری'), ('col', 'همکار'), ('fde', 'طراح'), ('nde', 'طراح غیرحضوری'), ('man', 'مدیریت'), ('opr', 'اپراتور'), ('pre', 'مدیریت داخلی'), ('acc', 'حسابدار'), ('itm', 'مدیر سایت'), ('new', 'عضو جدید')], default='csm', max_length=3),
        ),
        migrations.AlterField(
            model_name='usertg',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_tg', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
