# Generated by Django 3.0.1 on 2020-01-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200107_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس'},
        ),
        migrations.AlterModelOptions(
            name='introduction',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': 'ارتباط'},
        ),
        migrations.AlterModelOptions(
            name='usertg',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل کاربر'},
        ),
    ]
