# Generated by Django 5.2 on 2025-05-30 08:58

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=23, verbose_name='Tracking Code')),
                ('receiver_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Receiver Number')),
                ('counter', models.PositiveSmallIntegerField(default=1, verbose_name='Counter')),
                ('content', models.TextField(max_length=300)),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('panel', models.CharField(max_length=23)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Massage',
                'verbose_name_plural': 'Massages',
                'ordering': ['-send_date'],
            },
        ),
    ]
