# Generated by Django 5.2 on 2025-05-30 11:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0001_initial'),
        ('users', '0017_alter_employeelevelapiitemaccess_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_employee', to='massages.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_department', to='users.employee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(through='massages.EmployeeDepartment', through_fields=('department', 'employee'), to='users.employee'),
        ),
    ]
