# Generated by Django 5.2 on 2025-05-30 13:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massages', '0002_department_employeedepartment_department_employees'),
        ('users', '0018_address_city_address_state_alter_address_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=23, verbose_name='Tracking Code')),
                ('receiver_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Receiver Number')),
                ('counter', models.PositiveSmallIntegerField(default=1, verbose_name='Counter')),
                ('content', models.TextField(max_length=300)),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('panel', models.CharField(max_length=23)),
                ('status', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sms_massages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Massage',
                'verbose_name_plural': 'SMS Massages',
                'ordering': ['-send_date'],
            },
        ),
        migrations.CreateModel(
            name='WebMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, validators=[django.core.validators.MinLengthValidator(3)])),
                ('file_access', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('جدید', 'New'), ('پاسخ داده شده', 'Answered'), ('در انتظار پاسخ', 'Waiting'), ('بسته شده', 'Closed')], default='جدید', max_length=14)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_web_massage', to='massages.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_web_massage', to='users.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_web_massages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebMassageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ارسال', 'Send'), ('دریافت', 'Receive')], default='ارسال', max_length=6)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='massages.webmassage')),
            ],
        ),
        migrations.DeleteModel(
            name='Massage',
        ),
    ]
