# Generated by Django 5.2.1 on 2025-06-02 11:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymethod',
            name='public_method',
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is Public'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='description',
            field=models.TextField(blank=True, max_length=236, null=True),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='title',
            field=models.CharField(max_length=78, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='deliverymethodforrole',
            name='delivery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_list', to='delivery.deliverymethod', verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='delivery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_receipt_list', to='delivery.deliverymethod', verbose_name='Delivery Method'),
        ),
    ]
