# Generated by Django 5.2.1 on 2025-06-02 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_deliverymethod_public_method_and_more'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='delivery_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submit_delivery_receipt_list', to='employee.employee', verbose_name='Delivery Employee'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='status',
            field=models.CharField(choices=[('PEN', 'در انتظار'), ('REQ', 'درخواست'), ('SUB', 'ثبت شده'), ('END', 'تحویل داده شده')], default='PEN', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
