# Generated by Django 5.2.1 on 2025-06-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliveryreceipt_delivery_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverymethod',
            old_name='role',
            new_name='roles',
        ),
    ]
