# Generated by Django 5.2.1 on 2025-06-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_rename_role_deliverymethod_roles'),
        ('user', '0002_user_is_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethodforrole',
            name='delivery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_list', to='delivery.deliverymethod', verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='deliverymethodforrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_method_list', to='user.role'),
        ),
    ]
