# Generated by Django 3.0.1 on 2020-01-05 13:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0013_auto_20200105_1729'),
        ('order', '0009_cartaction_orderaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirm_date', models.DateTimeField(blank=True)),
                ('type', models.CharField(choices=[('csh', 'نقدی'), ('pos', 'کارتخوان'), ('dep', 'واریز'), ('gwy', 'درگاه')], max_length=3)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('confirm', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payments', to='order.Order')),
                ('record_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments_record', to='user.User_TG')),
            ],
        ),
    ]
