# Generated by Django 5.2 on 2025-04-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, unique=True)),
                ('national_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('economic_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('reg_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('address_text', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('accounting_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.IntegerField()),
                ('tmp_cashback', models.IntegerField()),
                ('cashback', models.IntegerField()),
                ('total_coin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_coin_amount', models.IntegerField()),
                ('now_coin_amount', models.IntegerField()),
                ('coin_description', models.TextField()),
                ('reg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('status', models.CharField(choices=[('act', 'Active'), ('exp', 'Expired'), ('use', 'Used')], default='act', max_length=3)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.credit')),
            ],
        ),
    ]
