# Generated by Django 5.2 on 2025-05-26 19:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'Coin', 'verbose_name_plural': 'Coins'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'verbose_name': 'Credit', 'verbose_name_plural': 'Credits'},
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='coin_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_text',
        ),
        migrations.AddField(
            model_name='company',
            name='address_content',
            field=models.TextField(blank=True, null=True, verbose_name='Address Content'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='base_coin_amount',
            field=models.IntegerField(verbose_name='Base Coin Amount'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_list', to='financial.credit'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='exp_date',
            field=models.DateField(verbose_name='Exp Date'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='now_coin_amount',
            field=models.IntegerField(verbose_name='Now Coin Amount'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='reg_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Reg Date'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='status',
            field=models.CharField(choices=[('فعال', 'Active'), ('منقضی', 'Expired'), ('استفاده شده', 'Used')], default='فعال', max_length=12),
        ),
        migrations.AlterField(
            model_name='company',
            name='accounting_id',
            field=models.PositiveBigIntegerField(verbose_name='Accounting ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='economic_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Economic number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='national_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='National number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='reg_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Reg Number'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='cashback',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_amount',
            field=models.BigIntegerField(verbose_name='Credit Amount'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='tmp_cashback',
            field=models.PositiveIntegerField(verbose_name='Tmp Cashback'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='total_coin',
            field=models.PositiveIntegerField(verbose_name='Total Coin'),
        ),
    ]
