# Generated by Django 3.0.1 on 2020-01-16 10:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200116_1414'),
        ('user', '0017_auto_20200116_1414'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirm_date', models.DateTimeField(blank=True)),
                ('type', models.CharField(choices=[('csh', 'نقدی'), ('pos', 'کارتخوان'), ('dep', 'واریز'), ('gwy', 'درگاه')], max_length=3)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('confirm', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payments', to='order.Order')),
                ('record_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments_record', to='user.UserTG')),
            ],
            options={
                'verbose_name': 'تراکنش های مالی',
                'verbose_name_plural': 'تراکنش های مالی',
            },
        ),
        migrations.DeleteModel(
            name='Financial',
        ),
    ]
