# Generated by Django 3.0.1 on 2020-01-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200116_1414'),
        ('user', '0017_auto_20200116_1414'),
        ('financial', '0002_auto_20200116_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialOrder',
            new_name='Transaction',
        ),
    ]
