# Generated by Django 5.2 on 2025-05-27 10:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_coin_options_alter_company_options_and_more'),
        ('orders', '0005_remove_order_class_id_cart_create_date_and_more'),
        ('users', '0013_remove_userprofile_company_remove_userprofile_credit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=37)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_number', models.PositiveIntegerField(default=0, verbose_name='Sort Number')),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Card Number')),
                ('bank_account_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Bank Account Number')),
                ('accounting_id', models.PositiveBigIntegerField(verbose_name='Accounting ID')),
            ],
            options={
                'verbose_name': 'Offline Bank Account',
                'verbose_name_plural': 'Offline Bank Accounts',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='OnlinePaymentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=37)),
                ('sort_number', models.PositiveIntegerField(default=0, verbose_name='Sort Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('accounting_id', models.PositiveBigIntegerField(verbose_name='Accounting ID')),
                ('detail', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Online Payment Module',
                'verbose_name_plural': 'Online Payment Modules',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.RemoveField(
            model_name='credit',
            name='cashback',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='tmp_cashback',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credit',
            name='total_amount',
            field=models.BigIntegerField(default=0, verbose_name='Total Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_credit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CashBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp_cashback', models.PositiveIntegerField(verbose_name='Tmp Cashback')),
                ('cashback', models.PositiveIntegerField()),
                ('percent', models.FloatField()),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cashback', to='financial.credit')),
            ],
            options={
                'verbose_name': 'Cash Back',
                'verbose_name_plural': 'Cash Backs',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(verbose_name='Total Price')),
                ('submit_date', models.DateField(default=django.utils.timezone.now, verbose_name='Submit Date')),
                ('deposit_date', models.DateField(blank=True, null=True, verbose_name='Deposit Date')),
                ('income', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('پرداخت آنلاین', 'Online'), ('کارت به کارت', 'Card'), ('نقد', 'Cash'), ('کارتخوان', 'Pos'), ('ثبت سفارش آنلاین', 'Online Submit'), ('ثبت سفارش حضوری', 'In Person Submit'), ('هزینه ارسال', 'Delivery'), ('بازگشت وجه', 'Pay'), ('سود اعتبار', 'Cashback'), ('تخفیف دستی', 'Discount'), ('پیش فاکتور', 'Not Yet'), ('لفو سفارش', 'Cancelled')], default='پرداخت آنلاین', max_length=16)),
                ('confirmed', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=100)),
                ('tracking_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tracking Code')),
                ('steps', models.JSONField(default=dict)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_deposit_list', to='orders.cart')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_confirmed_list', to='users.employee', verbose_name='Confirmed By')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_deposit', to='orders.order')),
                ('submit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_submit_list', to='users.employee', verbose_name='Submit By')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-submit_date'],
            },
        ),
        migrations.CreateModel(
            name='TurnOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_amount', models.BigIntegerField(verbose_name='Now Amount')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turn_over_list', to='financial.credit')),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='for_turn_over', to='financial.deposit')),
            ],
            options={
                'verbose_name': 'Turn Over',
                'verbose_name_plural': 'Turn Overs',
                'ordering': ['-deposit'],
            },
        ),
    ]
