# Generated by Django 5.2 on 2025-05-29 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_offlinebankaccount_onlinepaymentmodule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_product_income', models.PositiveIntegerField(verbose_name='Total Product Income')),
                ('total_options_income', models.PositiveIntegerField(verbose_name='Total Option Income')),
                ('sale_counter', models.PositiveIntegerField(verbose_name='Sale Counter')),
                ('total_delivery_income', models.PositiveIntegerField(verbose_name='Total Delivery Income')),
                ('total_discount', models.PositiveIntegerField(verbose_name='Total Discount Sale')),
            ],
            options={
                'verbose_name': 'Sale Report',
                'verbose_name_plural': 'Sale Reports',
                'ordering': ['-date'],
            },
        ),
    ]
