# Generated by Django 3.0.1 on 2020-01-16 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200116_1414'),
        ('order', '0016_auto_20200116_1414'),
        ('financial', '0003_auto_20200116_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=77, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('mode', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'نوع پرداخت/دریافت',
                'verbose_name_plural': 'نوع پرداخت/دریافت',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_transaction', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='record_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_transaction_record', to='user.UserTG'),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('base_salary', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('reduce_salary', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('for_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_salary', to='user.UserTG')),
                ('record_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_salary_payment_record', to='user.UserTG')),
            ],
            options={
                'verbose_name': 'حقوق ها',
                'verbose_name_plural': 'حقوق ها',
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('record_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_financial_record', to='user.UserTG')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_type', to='financial.FinancialType')),
            ],
            options={
                'verbose_name': 'پرداخت/دریافت',
                'verbose_name_plural': 'پرداخت/دریافت',
            },
        ),
    ]
