# Generated by Django 5.2 on 2025-05-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_salereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleReport',
        ),
    ]
