# Generated by Django 3.0.1 on 2020-01-16 11:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200116_1414'),
        ('user', '0017_auto_20200116_1414'),
        ('financial', '0004_auto_20200116_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingHouse',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1)])),
                ('title', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'چاپخانه ها',
                'verbose_name_plural': 'چاپخانه ها',
            },
        ),
        migrations.CreateModel(
            name='PrintingHousePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_for_printing', to='order.Order')),
                ('printing_house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_payment', to='financial.PrintingHouse')),
                ('record_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_record_print_payment', to='user.UserTG')),
            ],
            options={
                'verbose_name': 'پرداختی به چاپخانه',
                'verbose_name_plural': 'پرداختی به چاپخانه',
            },
        ),
        migrations.CreateModel(
            name='PrintingHouseIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('printing_house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_income', to='financial.PrintingHouse')),
                ('record_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_record_print_income', to='user.UserTG')),
            ],
            options={
                'verbose_name': 'دریافتی از چاپخانه',
                'verbose_name_plural': 'دریافتی از چاپخانه',
            },
        ),
    ]
