# Generated by Django 5.2 on 2025-05-30 13:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_delete_salereport'),
        ('orders', '0006_exclusiveorder_description'),
        ('products', '0008_banner_gallerycategory_active_link_and_more'),
        ('users', '0018_address_city_address_state_alter_address_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('amount_type', models.CharField(choices=[('درصدی', 'Percent'), ('ثابت', 'Fix')], default='درصدی', max_length=5, verbose_name='Amount Type')),
                ('amount', models.FloatField()),
                ('max_discount_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Discount Price')),
                ('min_order_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Min Order Price')),
                ('discount_type', models.CharField(choices=[('فقط یک بار', 'One Time'), ('هر مشتری یک بار', 'One Per User'), ('نا محدود', 'Free'), ('اولین خرید', 'First Time')], default='نا محدود', max_length=15, verbose_name='Discount Type')),
                ('last_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Date')),
                ('max_use', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Use')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cart_discount', to='orders.cart')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_used', to='financial.discount')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_discounts', to='products.productcategory')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_categories', to='financial.discount')),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='product_category',
            field=models.ManyToManyField(through='financial.ProductCategoryDiscount', through_fields=('discount', 'category'), to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='RoleDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_roles', to='financial.discount')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_discounts', to='users.role')),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='role',
            field=models.ManyToManyField(through='financial.RoleDiscount', through_fields=('discount', 'role'), to='users.role'),
        ),
    ]
