# Generated by Django 5.2 on 2025-05-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_discount_discountused_productcategorydiscount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-last_date'], 'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='discountused',
            options={'ordering': ['cart'], 'verbose_name': 'Discount Used', 'verbose_name_plural': 'Discounts Used'},
        ),
        migrations.AlterModelOptions(
            name='productcategorydiscount',
            options={'ordering': ['discount'], 'verbose_name': 'Product Category Discount', 'verbose_name_plural': 'Product Category Discounts'},
        ),
        migrations.AlterModelOptions(
            name='rolediscount',
            options={'ordering': ['discount'], 'verbose_name': 'Role Discount', 'verbose_name_plural': 'Role Discounts'},
        ),
    ]
