# Generated by Django 5.2 on 2025-05-30 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_alter_discount_options_alter_discountused_options_and_more'),
        ('orders', '0006_exclusiveorder_description'),
        ('products', '0008_banner_gallerycategory_active_link_and_more'),
        ('users', '0018_address_city_address_state_alter_address_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=37, validators=[django.core.validators.MinLengthValidator(3)])),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('type', models.CharField(choices=[('تخفیف', 'Discount'), ('اعتبار', 'Credit')], default='تخفیف', max_length=7)),
                ('min_order_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Min Order Price')),
            ],
            options={
                'verbose_name': 'Festival',
                'verbose_name_plural': 'Festivals',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='discountused',
            options={'ordering': ['order'], 'verbose_name': 'Discount Used', 'verbose_name_plural': 'Discounts Used'},
        ),
        migrations.RemoveField(
            model_name='discountused',
            name='cart',
        ),
        migrations.AddField(
            model_name='discountused',
            name='order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='order_discount', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='type',
            field=models.CharField(choices=[('پرداخت آنلاین', 'Online'), ('کارت به کارت', 'Card'), ('نقد', 'Cash'), ('کارتخوان', 'Pos'), ('ثبت سفارش آنلاین', 'Online Submit'), ('ثبت سفارش حضوری', 'In Person Submit'), ('هزینه ارسال', 'Delivery'), ('بازگشت وجه', 'Pay'), ('سود اعتبار', 'Cashback'), ('تخفیف دستی', 'Free Discount'), ('کد تخفیف', 'Code Discount'), ('تخفیف جشنواره', 'Festival Discount'), ('اعتبار جشنواره', 'Festival Credit'), ('پیش فاکتور', 'Not Yet'), ('لفو سفارش', 'Cancelled')], default='پرداخت آنلاین', max_length=16),
        ),
        migrations.CreateModel(
            name='FestivalUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='festival_used', to='financial.festival')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_festival', to='orders.order')),
            ],
            options={
                'verbose_name': 'Festival Used',
                'verbose_name_plural': 'Festivals Used',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_type', models.CharField(choices=[('درصدی', 'Percent'), ('ثابت', 'Fix')], default='درصدی', max_length=5, verbose_name='Amount Type')),
                ('amount', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_festivals', to='products.productcategory')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_categories', to='financial.festival')),
            ],
            options={
                'verbose_name': 'Product Category Festival',
                'verbose_name_plural': 'Product Category Festivals',
                'ordering': ['festival'],
            },
        ),
        migrations.AddField(
            model_name='festival',
            name='product_category',
            field=models.ManyToManyField(through='financial.ProductCategoryFestival', through_fields=('festival', 'category'), to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='RoleFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_roles', to='financial.festival')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_festivals', to='users.role')),
            ],
            options={
                'verbose_name': 'Role Festival',
                'verbose_name_plural': 'Role Festivals',
                'ordering': ['festival'],
            },
        ),
        migrations.AddField(
            model_name='festival',
            name='role',
            field=models.ManyToManyField(through='financial.RoleFestival', through_fields=('festival', 'role'), to='users.role'),
        ),
    ]
