# Generated by Django 5.2.1 on 2025-06-02 11:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Seo title')),
                ('seo_description', models.TextField(blank=True, max_length=160, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Seo description')),
                ('seo_slug', models.SlugField(max_length=30, unique=True, verbose_name='Seo slug')),
                ('canonical_link', models.URLField(blank=True, null=True, verbose_name='Canonical link')),
                ('keywords', models.TextField(blank=True, max_length=236, null=True)),
                ('no_index', models.BooleanField(default=False, verbose_name='No index')),
                ('redirect_303_link', models.URLField(blank=True, null=True, verbose_name='Redirect 303 link')),
            ],
            options={
                'verbose_name': 'Metadata',
                'verbose_name_plural': 'Metadata',
            },
        ),
        migrations.CreateModel(
            name='LandingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=236, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('type', models.CharField(choices=[('MAN', 'صفحه اصلی'), ('PAG', 'صفحه ایستا'), ('DON', 'دانلود'), ('ART', 'مطلب'), ('PRO', 'محصولات')], default='PAG', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.IntegerField(default=0, verbose_name='Sort Number')),
                ('is_landing', models.BooleanField(default=False, verbose_name='Is Landing')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_categories', to='landing.landingcategory', verbose_name='Parent Category')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='landing_category', to='landing.metadata')),
            ],
            options={
                'verbose_name': 'Landing Category',
                'verbose_name_plural': 'Landing Categories',
                'ordering': ['parent_category', '-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_number', models.IntegerField(default=0, verbose_name='Sort Number')),
                ('page_size', models.CharField(choices=[('DEF', 'پیشفرض'), ('FUL', 'تمام صفحه'), ('HAF', 'نیم صفحه')], default='DEF', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Page Size')),
                ('write_date', models.DateField(default=django.utils.timezone.now, verbose_name='Write Date')),
                ('custom_style_class', models.CharField(blank=True, max_length=23, null=True, verbose_name='Custom Style Class')),
                ('hide_header', models.BooleanField(default=False, verbose_name='Hide Header')),
                ('hide_footer', models.BooleanField(default=False, verbose_name='Hide Footer')),
                ('writer_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_landing_list', to='employee.employee', verbose_name='Writer Employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landing_list', to='landing.landingcategory')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='landing', to='landing.metadata')),
            ],
            options={
                'verbose_name': 'Landing',
                'verbose_name_plural': 'Landings',
                'ordering': ['category', '-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('BAN', 'بنر'), ('HED', 'عنوان'), ('CAT', 'دسته بندی'), ('INF', 'اطلاعات محصول'), ('GAL', 'گالری'), ('VID', 'ویدیو'), ('BRF', 'معرفی'), ('CON', 'محتوا'), ('QUS', 'سوالات متداول'), ('TBL', 'جدول قیمت'), ('PAR', 'لندینگ مادر'), ('FRE', 'آزاد')], default='FRE', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Section Type')),
                ('section_order', models.IntegerField(default=0, verbose_name='Section Order')),
                ('elements', models.JSONField(default=dict)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_list', to='landing.landing')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['landing', '-section_order'],
            },
        ),
        migrations.CreateModel(
            name='VisualMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=78, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('type', models.CharField(choices=[('SLI', 'اسلاید شو'), ('TIM', 'گالری زماندار'), ('BOX', 'باکس تصویر')], max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('is_linked', models.BooleanField(default=False, verbose_name='Is Linked')),
                ('hyperlink', models.URLField(blank=True, null=True)),
                ('sort_number', models.IntegerField(default=0, verbose_name='Sort Number')),
                ('fields', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('landing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_visual_menu_list', to='landing.landing')),
            ],
            options={
                'verbose_name': 'Visual Menu',
                'verbose_name_plural': 'Visual Menus',
                'ordering': ['-sort_number', '-type'],
            },
        ),
    ]
