# Generated by Django 5.2.1 on 2025-06-02 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingcategory',
            name='type',
            field=models.CharField(choices=[('MAN', 'صفحه اصلی'), ('PAG', 'صفحه ایستا'), ('DON', 'دانلود'), ('ART', 'مطلب'), ('CAT', 'دسته محصول'), ('PRO', 'محصول')], default='PAG', max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
