"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3@=u-b!-k^t$g=!8n-9n*emjn^_j9r2s)qlw832rleoe*3k%vg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend',],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'api.throttles.BurstRateThrottle',
        'api.throttles.SustainedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': { # MEH: Handle spam request mostly
        'anon': '23/minute',
        'burst': '78/minute',
        'sustained': '1378/hour',
        'phone': '1/minute',
        'auth': '3/minute',
    }
}

# MEH: Refresh Token Timing!

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'TeamGraphic API',
    'DESCRIPTION': 'API for TeamGraphic BackEnd',
    'VERSION': '1.0.0',
    'TAGS': [
        {'name': 'Auth', 'description': 'Authentication Flows'},
        {'name': 'Role', 'description': 'Operations Related to Roles'},
        {'name': 'User', 'description': 'Operations Related to Users'},
        {'name': 'User-Address', 'description': 'Addresses for Users'},
        {'name': 'User-Introduction', 'description': 'Introduction for Users'},
        {'name': 'Employee', 'description': 'Operations Related to Employees'},
        {'name': 'Employee-Level', 'description': 'Operations Related to Employees Levels'},
        {'name': 'File-Manager', 'description': 'Operations Related to Files'},
        {'name': 'Design', 'description': 'Operations Related to Design'},
        {'name': 'Product-Category', 'description': 'Operations Related to Product Categories'},
        {'name': 'Product-Item', 'description': 'Operations Related to Products'},
        {'name': 'Product-Fields', 'description': 'Operations Related to Product Fields Config'},
        {'name': 'Gallery', 'description': 'Operations Related to Galleries'},
        {'name': 'Option', 'description': 'Operations Related to Product Options'},
        {'name': 'Price-List', 'description': 'Operations Related to Product Price List Table'},
        {'name': 'Message', 'description': 'Operations Related to Message (Alarm/SMS/Web Messages)'},
        {'name': 'Report', 'description': 'Operations Related to Reports'},
        {'name': 'Api-Access', 'description': 'Operations Related to Api Access Categories & Items (Only Admin)'},
    ],
    'SAVE_INCLUDE_SCHEMA': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'silk',
    'mptt',
    'django_filters',
    'api.apps.ApiConfig',
    'drf_material',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'django.contrib.gis',
    'django_celery_beat',
    'user.apps.UsersConfig',
    'city.apps.CityConfig',
    'employee.apps.EmployeeConfig',
    'financial.apps.FinancialConfig',
    'delivery.apps.DeliveryConfig',
    'product.apps.ProductConfig',
    'order.apps.OrderConfig',
    'message.apps.MessageConfig',
    'report.apps.ReportConfig',
    'landing.apps.LandingConfig',
    'config.apps.ConfigConfig',
    'file_manager.apps.FileManagerConfig',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.enrich_user.EnrichUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'silk.middleware.SilkyMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'teamgraphic_db',
        'USER': 'teamgraphic_admin',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/1'
# CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'user.User'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
