# Generated by Django 5.2.1 on 2025-06-02 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_manager', '0001_initial'),
        ('landing', '0002_alter_landingcategory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('code', models.CharField(default='000', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SheetPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('display_name', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Display Name')),
                ('description', models.TextField(blank=True, max_length=78, null=True)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('sheet_paper_number', models.PositiveSmallIntegerField(default=0, verbose_name='Sheet Paper Number')),
                ('purchase_price', models.PositiveIntegerField(default=0, verbose_name='Purchase Price')),
                ('cutting_price', models.PositiveIntegerField(default=0, verbose_name='Cutting Price')),
                ('inventory', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sheet Paper',
                'verbose_name_plural': 'Sheet Papers',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('display_name', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Display Name')),
                ('description', models.TextField(blank=True, max_length=78, null=True)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('base_cutting_edge', models.FloatField(default=0, verbose_name='Base Cutting Edge')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Tirage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Tirage',
                'verbose_name_plural': 'Tirages',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=78, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('active_link', models.BooleanField(default=False, verbose_name='Active Link')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_galleries', to='product.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=78, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gallery_image_list', to='product.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-sort_number', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=78, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=236, null=True)),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('status', models.CharField(choices=[('AC', 'فعال'), ('IN', 'غیر فعال'), ('UP', 'بروزرسانی')], default='AC', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('accounting_code', models.PositiveBigIntegerField(default=0, verbose_name='Accounting Code')),
                ('fast_order', models.BooleanField(default=True, verbose_name='Fast Order')),
                ('fast_order_title', models.CharField(blank=True, max_length=73, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Fast Order Title')),
                ('counting_unit', models.PositiveSmallIntegerField(blank=True, choices=[('عدد', 'Number'), ('تیراژ', 'Tirage')], default='عدد', null=True, verbose_name='Counting Unit')),
                ('free_order', models.BooleanField(default=True, verbose_name='Free Order')),
                ('round_price', models.CharField(choices=[(0, 'Base'), (10, 'R10'), (100, 'R100'), (1000, 'R1000')], default=1000, verbose_name='Round Price')),
                ('is_landing', models.BooleanField(default=True, verbose_name='Is Landing')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_product_category_list', to='product.gallerycategory')),
                ('landing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landing_product_category', to='landing.landing')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='product.productcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=78, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('type', models.CharField(choices=[('OFF', 'افست'), ('LAR', 'لارج فرمت'), ('DIG', 'دیجیتال'), ('ITM', 'محصول عمومی')], max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=236, null=True)),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('status', models.CharField(choices=[('AC', 'فعال'), ('IN', 'غیر فعال'), ('UP', 'بروزرسانی')], default='AC', max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
                ('accounting_code', models.PositiveBigIntegerField(default=0, verbose_name='Accounting Code')),
                ('price', models.JSONField(default=dict)),
                ('inventory', models.SmallIntegerField(default=-1)),
                ('is_landing', models.BooleanField(default=True, verbose_name='Is Landing')),
                ('total_order', models.PositiveIntegerField(default=0, verbose_name='Total Order')),
                ('last_order', models.DateField(blank=True, null=True, verbose_name='Last Order')),
                ('total_main_sale', models.PositiveIntegerField(default=0, verbose_name='Total Main Sale')),
                ('total_option_sale', models.PositiveIntegerField(default=0, verbose_name='Total Option Sale')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_product_list', to='product.gallerycategory')),
                ('landing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landing_product', to='landing.landing')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_list', to='product.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-sort_number', 'category'),
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=78, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=236, null=True)),
                ('base_price', models.PositiveIntegerField(default=0, verbose_name='Base Price')),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('avg_duration', models.PositiveSmallIntegerField(default=0, verbose_name='Average Duration')),
                ('total_order', models.PositiveSmallIntegerField(default=0, verbose_name='Total Order')),
                ('last_order', models.DateField(blank=True, null=True, verbose_name='Last Order')),
                ('total_sale', models.PositiveIntegerField(default=0, verbose_name='Total Sale')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='design_list', to='product.productcategory')),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
                'ordering': ['-sort_number', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('FAC', 'وجه'), ('SIZ', 'ابعاد'), ('PAP', 'جنس'), ('TIR', 'تیراژ'), ('COP', 'نسخه'), ('DES', 'طراحی'), ('UPF', 'فایل'), ('COL', 'رنگ'), ('DUR', 'تحویل کاری'), ('BAN', 'مشخصات بنر')], max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('filed_list', models.JSONField(default=dict)),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('price_type', models.CharField(choices=[('NON', 'ندارد'), ('FOR', 'فرمول'), ('MUL', 'ضریب'), ('ADD', 'اضافه'), ('MAN', 'دستی')], default='NON', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Price Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_field_list', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Field',
                'verbose_name_plural': 'Product Fields',
                'ordering': ['-sort_number', 'product'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_paper_weight', models.FloatField(default=0, verbose_name='Per-Paper Weight')),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('per_paper_price', models.PositiveIntegerField(default=0, verbose_name='Per-Paper Price')),
                ('color_print_price', models.PositiveIntegerField(default=0, verbose_name='Color Print Price')),
                ('baw_print_price', models.PositiveIntegerField(default=0, verbose_name='Baw Print Price')),
                ('sheet_paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_list', to='product.sheetpaper')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_list', to='product.size')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
                'ordering': ['sheet_paper'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=78, null=True)),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('download_counter', models.PositiveSmallIntegerField(default=0, verbose_name='Download Counter')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_file', to='file_manager.fileitem')),
            ],
            options={
                'verbose_name': 'Template File',
                'verbose_name_plural': 'Template Files',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_list', to='product.templatefile'),
        ),
    ]
