# Generated by Django 5.2.1 on 2025-06-02 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=236, null=True)),
                ('input_type', models.CharField(choices=[('CHE', 'چک باکس'), ('RAD', 'رادیو'), ('WAT', 'آبشاری'), ('NUM', 'عدد'), ('TXF', 'متن'), ('TXB', 'ناحیه متنی'), ('DAT', 'تاریخ'), ('FIL', 'فایل')], max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Input Type')),
                ('mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_numberize', models.BooleanField(default=True, verbose_name='Is Numberize')),
                ('in_formula', models.BooleanField(default=False, verbose_name='In Formula')),
                ('after_print', models.BooleanField(default=False, verbose_name='After Print')),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='product.optioncategory')),
            ],
            options={
                'verbose_name': 'Option Category',
                'verbose_name_plural': 'Option Categories',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=236, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('base_price', models.PositiveIntegerField(default=0, verbose_name='Base Price')),
                ('keyword', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_list', to='product.optioncategory')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['-sort_number', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_number', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Sort Number')),
                ('always_show', models.BooleanField(default=True, verbose_name='Always Show')),
                ('dependent_option', models.ManyToManyField(to='product.productoption')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='product.option')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_list', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Option',
                'verbose_name_plural': 'Product Options',
                'ordering': ['product', 'option', '-sort_number'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(through='product.ProductOption', through_fields=('product', 'option'), to='product.option'),
        ),
    ]
