# Generated by Django 5.2.1 on 2025-06-02 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_optioncategory_option_productoption_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=236, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
            ],
            options={
                'verbose_name': 'Price List Category',
                'verbose_name_plural': 'Price List Categories',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='PriceListTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=236, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Price List Table',
                'verbose_name_plural': 'Price List Tables',
            },
        ),
        migrations.CreateModel(
            name='PriceListTableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('size_column', models.BooleanField(default=False, verbose_name='Size Column')),
                ('size_unit', models.CharField(choices=[('CM', 'سانتی متر'), ('M', 'متر')], default='CM', max_length=2, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Size Unit')),
                ('duration_column', models.BooleanField(default=False, verbose_name='Duration Column')),
                ('gallery_column', models.BooleanField(default=False, verbose_name='Gallery Column')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_list', to='product.pricelistcategory')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_list', to='product.pricelisttable')),
            ],
            options={
                'verbose_name': 'Price List Table Category',
                'verbose_name_plural': 'Price List Table Categories',
                'ordering': ['category', 'table'],
            },
        ),
        migrations.AddField(
            model_name='pricelisttable',
            name='price_list_categories',
            field=models.ManyToManyField(through='product.PriceListTableCategory', through_fields=('table', 'category'), to='product.pricelistcategory', verbose_name='Price List Categories'),
        ),
        migrations.CreateModel(
            name='PriceListTableProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_table_list', to='product.productcategory')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_list', to='product.pricelisttable')),
            ],
            options={
                'verbose_name': 'Price List Table Product Category',
                'verbose_name_plural': 'Price List Table Product Categories',
                'ordering': ['product_category', 'table'],
            },
        ),
        migrations.AddField(
            model_name='pricelisttable',
            name='product_categories',
            field=models.ManyToManyField(through='product.PriceListTableProductCategory', through_fields=('table', 'product_category'), to='product.productcategory', verbose_name='Product Categories'),
        ),
        migrations.CreateModel(
            name='PriceListTableProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('tirage_row', models.BooleanField(default=False, verbose_name='Tirage Row')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='product.pricelisttableproductcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_table_list', to='product.product')),
            ],
            options={
                'verbose_name': 'Price List Table Product Item',
                'verbose_name_plural': 'Price List Table Product Items',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.AddField(
            model_name='pricelisttableproductcategory',
            name='items',
            field=models.ManyToManyField(through='product.PriceListTableProductItem', through_fields=('price_list', 'product'), to='product.product'),
        ),
    ]
