# Generated by Django 5.2.1 on 2025-06-02 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_pricelistcategory_pricelisttable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('punch_price', models.PositiveIntegerField(default=0, verbose_name='Punch Price')),
                ('leaf_size', models.PositiveSmallIntegerField(default=0, verbose_name='Leaf Size')),
                ('leaf_price', models.FloatField(default=0, verbose_name='Leaf Price')),
                ('white_price', models.FloatField(default=0, verbose_name='White Price')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['title'],
            },
        ),
    ]
