# Generated by Django 5.2.1 on 2025-06-02 11:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=78, validators=[django.core.validators.MinLengthValidator(1)])),
                ('create_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Create Date')),
                ('volume', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_directory_list', to='employee.employee')),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_dirs', to='file_manager.filedirectory', verbose_name='Parent Directory')),
            ],
            options={
                'verbose_name': 'File Directory',
                'verbose_name_plural': 'File Directories',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=78, validators=[django.core.validators.MinLengthValidator(1)])),
                ('type', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(1)])),
                ('upload_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Upload Date')),
                ('volume', models.IntegerField(default=0)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_files', to='file_manager.filedirectory')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_file_list', to='employee.employee')),
            ],
            options={
                'verbose_name': 'File Item',
                'verbose_name_plural': 'File Items',
                'ordering': ['-upload_date', 'directory'],
            },
        ),
    ]
