# Generated by Django 5.2.1 on 2025-06-02 11:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('user', '0002_user_is_employee_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=26, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('content', models.TextField(max_length=236)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_alarm_massage_list', to='employee.employee')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_massage_list', to='user.role')),
            ],
            options={
                'verbose_name': 'Alarm Massage',
                'verbose_name_plural': 'Alarms Massage',
                'ordering': ['-start_date'],
            },
        ),
    ]
