# Generated by Django 5.2.1 on 2025-06-02 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=37, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.IntegerField(default=0, verbose_name='Sort Number')),
            ],
            options={
                'verbose_name': 'API Category',
                'verbose_name_plural': 'API Categories',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='ApiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=37, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.IntegerField(default=0, verbose_name='Sort Number')),
                ('key', models.CharField(max_length=37, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'verbose_name': 'API Item',
                'verbose_name_plural': 'API Items',
                'ordering': ['-sort_number'],
            },
        ),
    ]
