# Generated by Django 5.2 on 2025-05-26 12:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_employeelevel_introduction_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('description', models.TextField(max_length=100)),
                ('submit_date', models.DateTimeField(default=datetime.datetime.now)),
                ('delivery_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_receipt_list', to='users.employee')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_receipt_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
