# Generated by Django 5.2 on 2025-05-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryCategory',
        ),
        migrations.DeleteModel(
            name='DeliveryMethod',
        ),
        migrations.DeleteModel(
            name='DeliveryReceipt',
        ),
    ]
