# Generated by Django 5.2 on 2025-05-26 18:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0002_delete_deliverycategory_delete_deliverymethod_and_more'),
        ('users', '0010_alter_introduction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.IntegerField(default=0, verbose_name='Sort Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Delivery Category',
                'verbose_name_plural': 'Delivery Categories',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.IntegerField(default=0, verbose_name='Sort Number')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('states', models.JSONField(blank=True, default=dict, null=True)),
                ('cities', models.JSONField(blank=True, default=dict, null=True)),
                ('need_tracking_code', models.BooleanField(default=False, verbose_name='Need Tracking Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('main_price', models.IntegerField(default=0, verbose_name='Main Price')),
                ('public_method', models.BooleanField(default=True, verbose_name='Public Method')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_method_list', to='deliveries.deliverycategory')),
            ],
            options={
                'verbose_name': 'Delivery Method',
                'verbose_name_plural': 'Delivery Methods',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryForRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_method_list', to='users.role')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_role', to='deliveries.deliverymethod', verbose_name='Delivery Method')),
            ],
            options={
                'verbose_name': 'Delivery For Roll',
                'verbose_name_plural': 'Deliveries For Rolls',
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Postal Code')),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True, verbose_name='Request Date')),
                ('status', models.CharField(choices=[('در انتظار', 'Pending'), ('درخواست', 'Requested'), ('ثبت شده', 'Submitted')], default='در انتظار', max_length=10, validators=[django.core.validators.MinLengthValidator(3)])),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date')),
                ('delivery_code', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Delivery Code')),
                ('tracking_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tracking Code')),
                ('tracking_code_date', models.DateTimeField(blank=True, null=True, verbose_name='Tracking Code Date')),
                ('price', models.IntegerField(default=0)),
                ('delivery_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_submit_list', to='users.employee', verbose_name='Delivery Employee')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_method_in_receipt', to='deliveries.deliverymethod', verbose_name='Delivery Method')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_receipt_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Receipt',
                'verbose_name_plural': 'Delivery Receipts',
                'ordering': ['request_date'],
            },
        ),
    ]
