# Generated by Django 5.2 on 2025-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_initial'),
        ('users', '0010_alter_introduction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='role',
            field=models.ManyToManyField(through='deliveries.DeliveryForRoll', through_fields=('delivery_method', 'role'), to='users.role'),
        ),
    ]
