# Generated by Django 5.2 on 2025-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_deliverymethod_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycategory',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
    ]
