# Generated by Django 5.2 on 2025-05-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_alter_deliverycategory_sort_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryforroll',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='main_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Main Price'),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
