# Generated by Django 5.2.1 on 2025-06-02 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_levels_create', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Level',
                'verbose_name_plural': 'Employee Levels',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_list', to='employee.employeelevel'),
        ),
        migrations.CreateModel(
            name='EmployeeLevelAccessApiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employee_levels', to='api.apiitem')),
                ('employee_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_api_items', to='employee.employeelevel')),
            ],
            options={
                'verbose_name': 'Employee Level Access API Item',
                'verbose_name_plural': 'Employee Levels Access API Items',
            },
        ),
        migrations.AddField(
            model_name='employeelevel',
            name='api_items',
            field=models.ManyToManyField(through='employee.EmployeeLevelAccessApiItem', through_fields=('employee_level', 'api_item'), to='api.apiitem', verbose_name='Api Items'),
        ),
    ]
