# Generated by Django 5.2 on 2025-05-19 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('color_code', models.CharField(default='000', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=37, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('base_price', models.IntegerField(default=0)),
                ('sort_number', models.IntegerField(default=0)),
                ('avg_duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format_name', models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('sort_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_name', models.CharField(max_length=73, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('gallery_alt', models.CharField(max_length=73, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=73, validators=[django.core.validators.MinLengthValidator(3)])),
                ('image_alt', models.CharField(max_length=73, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=23, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_price', models.IntegerField(default=0)),
                ('is_number', models.BooleanField(default=False)),
                ('sort_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category_name', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('input_type', models.CharField(choices=[('چک باکس', 'Checkbox'), ('رادیو', 'Radiobutton'), ('آبشاری', 'Waterfall'), ('متن', 'Textfield'), ('ناحیه متنی', 'Textbox'), ('تاریخ', 'Date'), ('فایل', 'File')], max_length=10, validators=[django.core.validators.MinLengthValidator(3)])),
                ('mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('hidden_price', models.BooleanField(default=False)),
                ('after_print', models.BooleanField(default=False)),
                ('sort_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=73, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('product_type', models.CharField(choices=[('افست', 'Offset'), ('لارج فرمت', 'Large Format'), ('دیجیتال', 'Digital'), ('محصول', 'Item'), ('سایر', 'Other')], max_length=10, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('sort_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('فعال', 'Active'), ('غیر فعال', 'Inactive'), ('بروزرسانی', 'Updating')], default='غیر فعال', max_length=10, validators=[django.core.validators.MinLengthValidator(3)])),
                ('private', models.BooleanField(default=False)),
                ('accounting_code', models.IntegerField(default=0)),
                ('base_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=73, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('sort_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('فعال', 'Active'), ('غیر فعال', 'Inactive'), ('بروزرسانی', 'Updating')], default='غیر فعال', max_length=10, validators=[django.core.validators.MinLengthValidator(3)])),
                ('accounting_code', models.IntegerField(default=0)),
                ('short_order', models.BooleanField(default=True)),
                ('short_order_title', models.CharField(blank=True, max_length=73, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('counting_unit', models.CharField(blank=True, choices=[('عدد', 'Number'), ('تیراژ', 'Tirage')], default='عدد', max_length=10, null=True)),
                ('free_order', models.BooleanField(default=True)),
                ('round_price', models.CharField(choices=[('0', 'Rn'), ('10', 'R10'), ('100', 'R100'), ('1000', 'R1000')], default='0', max_length=4)),
                ('is_landing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('سایز', 'Size'), ('تیراژ', 'Tirage'), ('نسخه', 'Copies'), ('قالب', 'Template'), ('فایل', 'Upload File'), ('رنگ', 'Color')], max_length=10, validators=[django.core.validators.MinLengthValidator(3)])),
                ('field_json', models.JSONField(default=dict)),
                ('sort_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('display_name', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, max_length=73, null=True)),
                ('length', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('base_cutting_edge', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=73, null=True)),
                ('sort_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tirage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
            ],
        ),
    ]
