# Generated by Django 5.2 on 2025-05-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='products.productcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_galleries', to='products.gallerycategory'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='products.gallerycategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_list', to='products.gallerycategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata_product', to='pages.metadata'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_list', to='products.gallerycategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='landing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landing_category', to='pages.landing'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata_category', to='pages.metadata'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='productfield',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatefile',
            name='file_format',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='products.filetype'),
            preserve_default=False,
        ),
    ]
