# Generated by Django 5.2 on 2025-05-26 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_design_category_gallerycategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color_name'], 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['-sort_number'], 'verbose_name': 'Design', 'verbose_name_plural': 'Designs'},
        ),
        migrations.AlterModelOptions(
            name='filetype',
            options={'ordering': ['-sort_number'], 'verbose_name': 'File Type', 'verbose_name_plural': 'File Types'},
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['-sort_number'], 'verbose_name': 'Gallery Category', 'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-sort_number', 'category'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['-sort_number'], 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='optioncategory',
            options={'ordering': ['-sort_number'], 'verbose_name': 'Option Category', 'verbose_name_plural': 'Option Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productfield',
            options={'ordering': ['-sort_number', 'product', 'product__category'], 'verbose_name': 'Product Field', 'verbose_name_plural': 'Product Fields'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['display_name'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AlterModelOptions(
            name='templatefile',
            options={'ordering': ['-sort_number'], 'verbose_name': 'Template File', 'verbose_name_plural': 'Template Files'},
        ),
        migrations.AlterModelOptions(
            name='tirage',
            options={'ordering': ['amount'], 'verbose_name': 'Tirage', 'verbose_name_plural': 'Tirages'},
        ),
        migrations.RenameField(
            model_name='gallerycategory',
            old_name='gallery_alt',
            new_name='gallery_image_alt',
        ),
        migrations.RemoveField(
            model_name='option',
            name='is_number',
        ),
        migrations.RemoveField(
            model_name='option',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='optioncategory',
            name='service_category_name',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='short_order',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='short_order_title',
        ),
        migrations.AddField(
            model_name='option',
            name='is_numberize',
            field=models.BooleanField(default=False, verbose_name='Is Numberize'),
        ),
        migrations.AddField(
            model_name='option',
            name='option_name',
            field=models.CharField(default=0, max_length=23, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Option Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optioncategory',
            name='option_category_name',
            field=models.CharField(default=0, max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Option Category Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='fast_order',
            field=models.BooleanField(default=True, verbose_name='Fast Order'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='fast_order_title',
            field=models.CharField(blank=True, max_length=73, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Fast Order Title'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(default='000', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Color Code'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Color Name'),
        ),
        migrations.AlterField(
            model_name='design',
            name='avg_duration',
            field=models.IntegerField(default=0, verbose_name='Average Duration'),
        ),
        migrations.AlterField(
            model_name='design',
            name='base_price',
            field=models.IntegerField(default=0, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='design',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='file_format_name',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='File Format Name'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='gallery_name',
            field=models.CharField(max_length=73, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Gallery Name'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_images', to='products.gallerycategory'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_alt',
            field=models.CharField(max_length=73, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Image Alt'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_name',
            field=models.CharField(max_length=73, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Image Name'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='option',
            name='base_price',
            field=models.IntegerField(default=0, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='option',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='optioncategory',
            name='after_print',
            field=models.BooleanField(default=False, verbose_name='After Print'),
        ),
        migrations.AlterField(
            model_name='optioncategory',
            name='hidden_price',
            field=models.BooleanField(default=False, verbose_name='Hidden Price'),
        ),
        migrations.AlterField(
            model_name='optioncategory',
            name='input_type',
            field=models.CharField(choices=[('چک باکس', 'Checkbox'), ('رادیو', 'Radiobutton'), ('آبشاری', 'Waterfall'), ('متن', 'Textfield'), ('ناحیه متنی', 'Textbox'), ('تاریخ', 'Date'), ('فایل', 'File')], max_length=10, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Input Type'),
        ),
        migrations.AlterField(
            model_name='optioncategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='optioncategory',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='accounting_code',
            field=models.IntegerField(default=0, verbose_name='Accounting Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(default=0, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_product_list', to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gallery_product_list', to='products.gallerycategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=73, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('افست', 'Offset'), ('لارج فرمت', 'Large Format'), ('دیجیتال', 'Digital'), ('محصول', 'Item'), ('سایر', 'Other')], max_length=10, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='accounting_code',
            field=models.IntegerField(default=0, verbose_name='Accounting Code'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=73, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='counting_unit',
            field=models.CharField(blank=True, choices=[('عدد', 'Number'), ('تیراژ', 'Tirage')], default='عدد', max_length=10, null=True, verbose_name='Counting Unit'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='free_order',
            field=models.BooleanField(default=True, verbose_name='Free Order'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_landing',
            field=models.BooleanField(default=True, verbose_name='Is Landing'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='products.productcategory', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='round_price',
            field=models.CharField(choices=[('0', 'Rn'), ('10', 'R10'), ('100', 'R100'), ('1000', 'R1000')], default='0', max_length=4, verbose_name='Round Price'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='field_json',
            field=models.JSONField(default=dict, verbose_name='Field JSON List'),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='field_name',
            field=models.CharField(choices=[('سایز', 'Size'), ('تیراژ', 'Tirage'), ('نسخه', 'Copies'), ('قالب', 'Template'), ('فایل', 'Upload File'), ('رنگ', 'Color')], max_length=10, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_fields', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='size',
            name='base_cutting_edge',
            field=models.IntegerField(default=0, verbose_name='Base Cutting Edge'),
        ),
        migrations.AlterField(
            model_name='size',
            name='display_name',
            field=models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='templatefile',
            name='file_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.filetype', verbose_name='File Format'),
        ),
        migrations.AlterField(
            model_name='templatefile',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='templatefile',
            name='template_name',
            field=models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Template Name'),
        ),
    ]
