# Generated by Django 5.2 on 2025-05-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_color_options_alter_design_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_designs', to='products.productcategory'),
        ),
    ]
