# Generated by Django 5.2 on 2025-05-26 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_design_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.RenameField(
            model_name='design',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='gallerycategory',
            old_name='gallery_image_alt',
            new_name='alt',
        ),
        migrations.RenameField(
            model_name='templatefile',
            old_name='template_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='color',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='color',
            name='color_name',
        ),
        migrations.RemoveField(
            model_name='filetype',
            name='file_format_name',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='gallery_name',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_name',
        ),
        migrations.RemoveField(
            model_name='optioncategory',
            name='option_category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='field_json',
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='field_name',
        ),
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(default='000', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default=0, max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filetype',
            name='file_format',
            field=models.CharField(default=0, max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='File Format'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='title',
            field=models.CharField(default=0, max_length=73, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt',
            field=models.CharField(default=0, max_length=73, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(default=0, max_length=73, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='title',
            field=models.CharField(default=0, max_length=23, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optioncategory',
            name='title',
            field=models.CharField(default=0, max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=0, max_length=73, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('افست', 'Offset'), ('لارج فرمت', 'Large Format'), ('دیجیتال', 'Digital'), ('محصول', 'Item'), ('سایر', 'Other')], default=0, max_length=10, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title',
            field=models.CharField(default=0, max_length=73, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfield',
            name='detail',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='productfield',
            name='title',
            field=models.CharField(choices=[('سایز', 'Size'), ('تیراژ', 'Tirage'), ('نسخه', 'Copies'), ('قالب', 'Template'), ('فایل', 'Upload File'), ('رنگ', 'Color')], default=0, max_length=10, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design',
            name='avg_duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Average Duration'),
        ),
        migrations.AlterField(
            model_name='design',
            name='base_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='design',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='option',
            name='base_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='option',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='optioncategory',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='accounting_code',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Accounting Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='accounting_code',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Accounting Code'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='size',
            name='base_cutting_edge',
            field=models.FloatField(default=0, verbose_name='Base Cutting Edge'),
        ),
        migrations.AlterField(
            model_name='size',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='templatefile',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
