# Generated by Django 5.2 on 2025-05-29 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_color_options_rename_name_design_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='total_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Order'),
        ),
        migrations.AddField(
            model_name='design',
            name='total_sale',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_main_sale',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Main Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_option_sale',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Option Sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Order'),
        ),
        migrations.AddField(
            model_name='templatefile',
            name='download_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Download Count'),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='title',
            field=models.CharField(choices=[('سایز', 'Size'), ('تیراژ', 'Tirage'), ('نسخه', 'Copies'), ('قالب', 'Template'), ('فایل', 'Upload File'), ('رنگ', 'Color'), ('تحویل کاری', 'Duration')], max_length=10, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
