# Generated by Django 5.2 on 2025-05-30 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_design_total_order_design_total_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
            ],
            options={
                'verbose_name': 'Price List Category',
                'verbose_name_plural': 'Price List Categories',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='PriceListTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('size_column', models.BooleanField(default=False, verbose_name='Size Column')),
                ('duration_column', models.BooleanField(default=False, verbose_name='Duration Column')),
                ('gallery_column', models.BooleanField(default=False, verbose_name='Gallery Column')),
            ],
            options={
                'verbose_name': 'Price List Table',
                'verbose_name_plural': 'Price List Tables',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='PriceListTableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_tables', to='products.pricelistcategory')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_categories', to='products.pricelisttable')),
            ],
            options={
                'verbose_name': 'Price List Table Category',
                'verbose_name_plural': 'Price List Table Categories',
                'ordering': ['category', 'table'],
            },
        ),
        migrations.AddField(
            model_name='pricelisttable',
            name='price_list_categories',
            field=models.ManyToManyField(through='products.PriceListTableCategory', through_fields=('table', 'category'), to='products.pricelistcategory', verbose_name='Price List Categories'),
        ),
        migrations.CreateModel(
            name='PriceListTableProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_price_tables', to='products.productcategory')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_product_categories', to='products.pricelisttable')),
            ],
            options={
                'verbose_name': 'Price List Table Product',
                'verbose_name_plural': 'Price List Table Products',
                'ordering': ['product_category', 'table'],
            },
        ),
        migrations.AddField(
            model_name='pricelisttable',
            name='product_categories',
            field=models.ManyToManyField(through='products.PriceListTableProductCategory', through_fields=('table', 'product_category'), to='products.productcategory', verbose_name='Product Categories'),
        ),
        migrations.CreateModel(
            name='PriceListTableProductItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
                ('tirage_row', models.BooleanField(default=False, verbose_name='Tirage Row')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_product', to='products.pricelisttableproductcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_price_tables', to='products.product')),
            ],
            options={
                'verbose_name': 'Price List Table Product Item',
                'verbose_name_plural': 'Price List Table Product Items',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.AddField(
            model_name='pricelisttableproductcategory',
            name='items',
            field=models.ManyToManyField(through='products.PriceListTableProductItems', through_fields=('price_list', 'product'), to='products.product'),
        ),
    ]
