# Generated by Django 5.2 on 2025-05-30 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pricelistcategory_pricelisttable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='active_link',
            field=models.BooleanField(default=False, verbose_name='Active Link'),
        ),
        migrations.AddField(
            model_name='pricelisttable',
            name='size_unit',
            field=models.CharField(choices=[('سانتی متر', 'Cm'), ('متر', 'M')], default='سانتی متر', max_length=9, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Size Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_order',
            field=models.DateField(blank=True, null=True, verbose_name='Last Order'),
        ),
    ]
