# Generated by Django 5.2 on 2025-05-30 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_banner_gallerycategory_active_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='alt',
            field=models.CharField(default=0, max_length=73, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelistcategory',
            name='alt',
            field=models.CharField(default=0, max_length=73, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(default=0, max_length=73, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='alt',
            field=models.CharField(default=0, max_length=73, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatefile',
            name='alt',
            field=models.CharField(default=0, max_length=73, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
    ]
