# Generated by Django 3.0.1 on 2019-12-31 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cost', models.PositiveIntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, max_length=777)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=0)),
                ('ready_date', models.DateField()),
                ('cost', models.IntegerField(default=-1)),
            ],
        ),
    ]
