# Generated by Django 3.0.1 on 2020-01-02 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '__first__'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('rec', 'در حال ثبت'), ('chk', 'در حال بررسی'), ('pre', 'آماده سازی'), ('rdy', 'آماده تحویل'), ('del', 'آماده ارسال'), ('snd', 'ارسال شد'), ('get', 'تحویل داده شد'), ('can', 'لغو شده'), ('rem', 'صورت حساب مانده')], default='rec', max_length=3)),
                ('total_cost', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=0)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_cart', to='delivery.Delivery')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_carts', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('vector', models.ImageField(upload_to='')),
                ('type', models.IntegerField(choices=[('1', 'تایید'), ('-1', 'لغو'), ('0', 'بررسی')])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('design_feature', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, max_length=777)),
                ('duration', models.IntegerField(default=0)),
                ('ready_date', models.DateField()),
                ('cost', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_orders', to='order.Cart')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_orders', to='order.Status')),
            ],
        ),
    ]
