# Generated by Django 3.0.1 on 2020-01-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('2', 'تایید'), ('0', 'لغو'), ('1', 'بررسی')], max_length=1),
        ),
    ]
