# Generated by Django 3.0.1 on 2020-01-04 09:28

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200102_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='vector',
            field=models.ImageField(upload_to=order.models.status_vector_directory_path),
        ),
    ]
