# Generated by Django 3.0.1 on 2019-12-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('vector', models.ImageField(upload_to='')),
                ('type', models.IntegerField(choices=[('1', 'تایید'), ('-1', 'لغو'), ('0', 'بررسی')])),
            ],
        ),
    ]
