# Generated by Django 3.0.1 on 2019-12-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('rec', 'در حال ثبت'), ('chk', 'در حال بررسی'), ('pre', 'آماده سازی'), ('rdy', 'آماده تحویل'), ('sub', 'آماده ارسال'), ('snd', 'در حال ارسال'), ('del', 'تحویل داده شد'), ('can', 'لغو شده'), ('rem', 'صورت حساب مانده')], default='rec', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_orders', to='order.Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_orders', to='order.Cart'),
        ),
    ]
