# Generated by Django 3.0.1 on 2019-12-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191231_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_feature',
            field=models.BooleanField(default=False),
        ),
    ]
