# Generated by Django 3.0.1 on 2020-01-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200105_1043'),
        ('order', '0007_remove_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_carts', to='user.User_TG'),
        ),
    ]
