# Generated by Django 3.0.1 on 2020-01-05 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200105_1043'),
        ('order', '0008_auto_20200105_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_actions_new', to='order.Status')),
                ('old_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_actions_old', to='order.Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_all_actions', to='order.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions_on_order', to='user.User_TG')),
            ],
        ),
        migrations.CreateModel(
            name='CartAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('rec', 'در حال ثبت'), ('chk', 'در حال بررسی'), ('pre', 'آماده سازی'), ('rdy', 'آماده تحویل'), ('del', 'آماده ارسال'), ('snd', 'ارسال شد'), ('get', 'تحویل داده شد'), ('can', 'لغو شده'), ('rem', 'صورت حساب مانده')], max_length=3)),
                ('new_status', models.CharField(choices=[('rec', 'در حال ثبت'), ('chk', 'در حال بررسی'), ('pre', 'آماده سازی'), ('rdy', 'آماده تحویل'), ('del', 'آماده ارسال'), ('snd', 'ارسال شد'), ('get', 'تحویل داده شد'), ('can', 'لغو شده'), ('rem', 'صورت حساب مانده')], max_length=3)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_all_actions', to='order.Cart')),
            ],
        ),
    ]
