# Generated by Django 3.0.1 on 2020-01-12 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20200112_1723'),
        ('order', '0009_cartaction_orderaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.AddField(
            model_name='order',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_in_orders', to='product.Design'),
        ),
        migrations.AddField(
            model_name='order',
            name='design_cost',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_orders', to='product.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_cost',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tot_cost',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(99999999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('rec', 'در حال ثبت'), ('chk', 'ثبت شده و در حال بررسی'), ('pre', 'آماده سازی'), ('rdy', 'آماده تحویل'), ('del', 'آماده ارسال'), ('snd', 'ارسال شد'), ('get', 'تحویل داده شد'), ('can', 'لغو شده'), ('rem', 'صورت حساب مانده')], default='rec', max_length=3),
        ),
        migrations.AlterField(
            model_name='cartaction',
            name='new_status',
            field=models.CharField(choices=[('rec', 'در حال ثبت'), ('chk', 'ثبت شده و در حال بررسی'), ('pre', 'آماده سازی'), ('rdy', 'آماده تحویل'), ('del', 'آماده ارسال'), ('snd', 'ارسال شد'), ('get', 'تحویل داده شد'), ('can', 'لغو شده'), ('rem', 'صورت حساب مانده')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cartaction',
            name='old_status',
            field=models.CharField(choices=[('rec', 'در حال ثبت'), ('chk', 'ثبت شده و در حال بررسی'), ('pre', 'آماده سازی'), ('rdy', 'آماده تحویل'), ('del', 'آماده ارسال'), ('snd', 'ارسال شد'), ('get', 'تحویل داده شد'), ('can', 'لغو شده'), ('rem', 'صورت حساب مانده')], max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='design_feature',
            field=models.CharField(choices=[('new', 'سفارش طراحی'), ('snd', 'ارسال فایل طرح'), ('old', 'سفارش مجدد طرح قبلی'), ('non', 'بدون طرح')], default='snd', max_length=3),
        ),
    ]
