# Generated by Django 3.0.1 on 2020-01-12 14:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200112_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='older_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_order', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='design_cost',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_cost',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='tot_cost',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
