# Generated by Django 3.0.1 on 2020-01-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20200113_1731'),
        ('order', '0012_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_services',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='in_orders', through='product.OrderProductServices', to='product.ProductServices'),
        ),
    ]
