# Generated by Django 3.0.1 on 2020-01-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200116_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='cartaction',
            options={'verbose_name': 'تغییرات سبد خرید', 'verbose_name_plural': 'تغییرات سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش'},
        ),
        migrations.AlterModelOptions(
            name='orderaction',
            options={'verbose_name': 'تغییرات سفارش', 'verbose_name_plural': 'تغییرات سفارش'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'وضعیت های سفارش', 'verbose_name_plural': 'وضعیت های سفارش'},
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name': 'فایل ها', 'verbose_name_plural': 'فایل ها'},
        ),
    ]
