# Generated by Django 3.0.1 on 2020-01-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20200116_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='progress',
            field=models.BooleanField(default=False),
        ),
    ]
