# Generated by Django 3.0.1 on 2020-01-21 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_cart_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='order',
        ),
        migrations.AlterField(
            model_name='cart',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(choices=[('front', 'base1'), ('back', 'base2'), ('front_film', 'film1'), ('back_film', 'film2'), ('front_gold', 'gold1'), ('back_gold', 'gold2'), ('front_form', 'form1'), ('back_form', 'form2')], max_length=22),
        ),
    ]
