# Generated by Django 3.0.1 on 2020-01-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20200121_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_files', to='order.Order'),
        ),
    ]
