# Generated by Django 3.0.1 on 2020-01-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_uploadfile_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='user',
        ),
    ]
