# Generated by Django 3.0.1 on 2020-01-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200116_1414'),
        ('order', '0020_remove_uploadfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to='user.UserTG'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(choices=[('base1', 'front'), ('base2', 'back'), ('film1', 'front_film'), ('film2', 'back_film'), ('gold1', 'front_gold'), ('gold2', 'back_gold'), ('form1', 'front_form'), ('form2', 'back_form')], max_length=22),
        ),
    ]
