# Generated by Django 5.2 on 2025-04-26 08:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, unique=True)),
                ('national_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('economic_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('reg_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('address_text', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=25)),
                ('address_text', models.TextField()),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('plate_number', models.CharField(max_length=7)),
                ('unit_number', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undefined')], default='U', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('public_key', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('private_key', models.CharField(max_length=20)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_tg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
