# Generated by Django 5.2 on 2025-05-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_company_users_accounting_id_users_credit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['user__date_joined']},
        ),
    ]
