# Generated by Django 5.2 on 2025-05-03 11:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('users', '0003_alter_users_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undefined')], default='U', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('public_key', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('private_key', models.CharField(max_length=20)),
                ('accounting_id', models.IntegerField()),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('how_to', models.CharField(max_length=25)),
                ('job', models.CharField(blank=True, max_length=25, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.company')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.credit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__date_joined'],
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
