# Generated by Django 5.2 on 2025-05-03 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=1, max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
            preserve_default=False,
        ),
    ]
