# Generated by Django 5.2 on 2025-05-26 18:55

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introduction',
            options={'ordering': ['-sort_number'], 'verbose_name': 'Introduce', 'verbose_name_plural': 'Introduces'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='employeelevel',
            old_name='level_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='employeelevel',
            old_name='level_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_role',
            new_name='role',
        ),
        migrations.AddField(
            model_name='address',
            name='submit_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Submit Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employeelevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
    ]
