# Generated by Django 5.2 on 2025-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_introduction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accounting_id',
            field=models.PositiveBigIntegerField(verbose_name='Accounting ID'),
        ),
    ]
