# Generated by Django 5.2 on 2025-05-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_coin_options_alter_company_options_and_more'),
        ('users', '0011_alter_introduction_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_user', to='financial.credit'),
        ),
    ]
