# Generated by Django 5.2 on 2025-05-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='credit',
        ),
    ]
