# Generated by Django 5.2 on 2025-05-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userprofile_company_remove_userprofile_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accounting_name',
            field=models.CharField(blank=True, max_length=73, null=True, verbose_name='Accounting Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_order',
            field=models.DateField(blank=True, null=True, verbose_name='Last Order'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_main_buy',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Main Buy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_option_buy',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Option Buy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Order'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accounting_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Accounting ID'),
        ),
    ]
