# Generated by Django 5.2 on 2025-05-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
        ('users', '0014_userprofile_accounting_name_userprofile_last_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelevel',
            name='api_item',
            field=models.ManyToManyField(to='api.apiitem'),
        ),
        migrations.AddField(
            model_name='employeelevel',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee'),
        ),
    ]
