# Generated by Django 5.2 on 2025-05-30 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
        ('users', '0015_employeelevel_api_item_employeelevel_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelevel',
            name='api_item',
        ),
        migrations.CreateModel(
            name='EmployeeLevelApiItemAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employee_levels', to='api.apiitem')),
                ('employee_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_api_items', to='users.employeelevel')),
            ],
        ),
        migrations.AddField(
            model_name='employeelevel',
            name='api_items',
            field=models.ManyToManyField(through='users.EmployeeLevelApiItemAccess', through_fields=('employee_level', 'api_item'), to='api.apiitem', verbose_name='Api Items'),
        ),
    ]
