# Generated by Django 5.2 on 2025-05-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_employeelevel_api_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeelevelapiitemaccess',
            options={'verbose_name': 'Employee Level API Item Access', 'verbose_name_plural': 'Employee Level API Items Access'},
        ),
    ]
