# Generated by Django 5.2 on 2025-05-30 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_employeelevelapiitemaccess_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=37, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=23, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
