# Generated by Django 5.2 on 2025-05-19 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_size', models.CharField(choices=[('پیشفرض', 'Default'), ('تمام صفحه', 'Full')], default='پیشفرض', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('seo_description', models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('seo_slug', models.SlugField(max_length=100, unique=True)),
                ('canonical_link', models.URLField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, max_length=300, null=True)),
                ('no_index', models.BooleanField(default=False)),
                ('no_index_child', models.BooleanField(default=False)),
                ('parent_metadata', models.BooleanField(default=False)),
                ('redirect_303', models.BooleanField(default=False)),
                ('redirect_303_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('بنر', 'Banner'), ('عنوان', 'Title'), ('دسته بندی', 'Category'), ('اطلاعات', 'Info'), ('گالری', 'Gallery'), ('مقاله', 'Article'), ('سوالات', 'Question'), ('جدول قیمت', 'Price Table'), ('لندینگ مادر', 'Parent'), ('آزاد', 'Free')], max_length=23, validators=[django.core.validators.MinLengthValidator(3)])),
                ('section_order', models.IntegerField(default=0)),
                ('elements', models.JSONField(default=dict)),
            ],
        ),
    ]
