# Generated by Django 5.2 on 2025-05-19 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='landing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.landing'),
            preserve_default=False,
        ),
    ]
