# Generated by Django 5.2 on 2025-05-30 14:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_section_landing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landing',
            options={'ordering': ['category', '-sort_number'], 'verbose_name': 'Landing', 'verbose_name_plural': 'Landings'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'Metadata', 'verbose_name_plural': 'Metadata'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['landing', '-section_order'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='landing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='landing',
            name='metadata',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='metadata_landing', to='pages.metadata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landing',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AddField(
            model_name='landing',
            name='style',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='landing',
            name='title',
            field=models.CharField(default=0, max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='seo_title',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_order',
            field=models.IntegerField(default=0, verbose_name='Section Order'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('بنر', 'Banner'), ('عنوان', 'Title'), ('دسته بندی', 'Category'), ('اطلاعات', 'Info'), ('گالری', 'Gallery'), ('مقاله', 'Article'), ('سوالات', 'Question'), ('جدول قیمت', 'Price Table'), ('لندینگ مادر', 'Parent'), ('آزاد', 'Free')], max_length=23, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='section type'),
        ),
        migrations.CreateModel(
            name='LandingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('type', models.CharField(choices=[('صفحه ایستا', 'Page'), ('دانلود', 'Download'), ('مطلب', 'Article'), ('صفحه اصلی', 'Main'), ('محصولات', 'Category')], default='صفحه ایستا', max_length=10, validators=[django.core.validators.MinLengthValidator(4)])),
                ('sort_number', models.IntegerField(default=0, verbose_name='Sort Number')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='metadata_category_landing', to='pages.metadata')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_categories', to='pages.landingcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Landing Category',
                'verbose_name_plural': 'Landing Categories',
                'ordering': ['parent_category', '-sort_number'],
            },
        ),
        migrations.AddField(
            model_name='landing',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='landing_list', to='pages.landingcategory'),
            preserve_default=False,
        ),
    ]
