# Generated by Django 5.2 on 2025-05-30 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_landing_options_alter_metadata_options_and_more'),
        ('users', '0018_address_city_address_state_alter_address_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='alt',
            field=models.CharField(default=0, max_length=73, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landing',
            name='dif_footer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landing',
            name='dif_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landingcategory',
            name='alt',
            field=models.CharField(default=0, max_length=73, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('بنر', 'Banner'), ('عنوان', 'Title'), ('دسته بندی', 'Category'), ('اطلاعات محصول', 'Info'), ('گالری', 'Gallery'), ('ویدیو', 'Video'), ('مقاله', 'Article'), ('سوالات', 'Question'), ('جدول قیمت', 'Price Table'), ('لندینگ مادر', 'Parent'), ('آزاد', 'Free')], max_length=23, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='section type'),
        ),
        migrations.CreateModel(
            name='AlarmMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=37, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('content', models.TextField(max_length=300)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.role')),
            ],
        ),
        migrations.CreateModel(
            name='VisualMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=37, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('alt', models.CharField(max_length=73, validators=[django.core.validators.MinLengthValidator(3)])),
                ('linked', models.BooleanField(default=False)),
                ('hyperlink', models.URLField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('fields', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('landing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_visual_menu', to='pages.landing')),
            ],
        ),
    ]
