# Generated by Django 5.2 on 2025-05-30 15:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_landing_alt_landing_dif_footer_landing_dif_header_and_more'),
        ('users', '0018_address_city_address_state_alter_address_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmmassage',
            options={'ordering': ['-start_date'], 'verbose_name': 'Alarm Massage', 'verbose_name_plural': 'Alarms Massage'},
        ),
        migrations.AlterModelOptions(
            name='visualmenu',
            options={'ordering': ['-sort_order'], 'verbose_name': 'Visual Menu', 'verbose_name_plural': 'Visual Menus'},
        ),
        migrations.AddField(
            model_name='alarmmassage',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarm_massage_set', to='users.employee'),
        ),
        migrations.AddField(
            model_name='landing',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landing_set', to='users.employee'),
        ),
        migrations.AddField(
            model_name='visualmenu',
            name='type',
            field=models.CharField(choices=[('اسلاید شو', 'Slideshow'), ('گالری زماندار', 'Timer Gallery'), ('لندینگ', 'Landing')], default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmmassage',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarm_massages', to='users.role'),
        ),
        migrations.CreateModel(
            name='FileDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=73, validators=[django.core.validators.MinLengthValidator(1)])),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start Date')),
                ('volume', models.IntegerField(default=0, verbose_name='Volume')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_directory', to='users.employee')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_dirs', to='pages.filedirectory')),
            ],
            options={
                'verbose_name': 'File Directory',
                'verbose_name_plural': 'File Directories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=73, validators=[django.core.validators.MinLengthValidator(1)])),
                ('type', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(1)])),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start Date')),
                ('volume', models.IntegerField(default=0, verbose_name='Volume')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_files', to='pages.filedirectory')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_files', to='users.employee')),
            ],
            options={
                'verbose_name': 'File Item',
                'verbose_name_plural': 'Files Item',
                'ordering': ['-date'],
            },
        ),
    ]
