# Generated by Django 3.0.1 on 2020-01-02 10:33

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='جدید', max_length=20)),
                ('icon', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, max_length=2020)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to='')),
                ('preview', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=2020)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('code', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('cut_margin', models.FloatField()),
                ('safe_margin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('%', 'درصدی'), ('$', 'ثابت')], max_length=1)),
                ('amount', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ready',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('len', models.FloatField(verbose_name='length')),
                ('wid', models.FloatField(verbose_name='width')),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Template_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('tmp_file', models.FileField(upload_to=product.models.template_file_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Selling_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1000)),
                ('lat', models.BooleanField(default=False)),
                ('base_price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField()),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_body', to='product.Color')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_product', to='product.Discount')),
                ('ink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_ink', to='product.Color')),
                ('quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_product', to='product.Quality')),
                ('ready', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_product', to='product.Ready')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_product', to='product.Size')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=77)),
                ('preview', models.ImageField(upload_to='')),
                ('vector', models.ImageField(blank=True, upload_to='.')),
                ('properties', models.TextField(blank=True, max_length=2020)),
                ('brief_intro', models.TextField(blank=True, max_length=777)),
                ('long_intro', models.TextField(blank=True, max_length=5000)),
                ('guidance', models.TextField(blank=True, max_length=777)),
                ('design_feature', models.BooleanField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category')),
                ('selling_options', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Selling_Option')),
                ('template_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Template_File')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('preview', models.ImageField(upload_to='')),
                ('vector', models.ImageField(blank=True, upload_to='')),
                ('price', models.PositiveIntegerField(default=0)),
                ('min_time', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_inf', to='product.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Classification'),
        ),
    ]
