# Generated by Django 3.0.1 on 2019-12-31 15:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_selling_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_file',
            name='template_file',
        ),
        migrations.AlterField(
            model_name='template_file',
            name='tmp_file',
            field=models.FileField(upload_to=product.models.template_file_directory_path),
        ),
    ]
