# Generated by Django 3.0.1 on 2020-01-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200102_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_options',
        ),
        migrations.AddField(
            model_name='selling_option',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_options', to='product.Product'),
        ),
    ]
