# Generated by Django 3.0.1 on 2020-01-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191231_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling_option',
            name='side',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('None', 'غیر فعال'), ('1', 'یک رو'), ('2', 'دو رو')], default='None'),
        ),
    ]
