# Generated by Django 3.0.1 on 2020-01-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200102_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
