# Generated by Django 3.0.1 on 2020-01-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='low_price',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
