# Generated by Django 3.0.1 on 2020-01-04 07:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_design_low_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='icon',
            field=models.ImageField(upload_to=product.models.classification_icon_directory_pass),
        ),
        migrations.AlterField(
            model_name='classification',
            name='preview',
            field=models.ImageField(blank=True, upload_to=product.models.classification_preview_directory_pass),
        ),
    ]
