# Generated by Django 3.0.1 on 2020-01-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200102_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling_option',
            name='side',
            field=models.CharField(blank=True, choices=[('0', 'غیر فعال'), ('1', 'یک رو'), ('2', 'دو رو')], default='0', max_length=1),
        ),
    ]
