# Generated by Django 3.0.1 on 2020-01-04 08:42

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200104_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to=product.models.category_icon_directory_pass),
        ),
        migrations.AlterField(
            model_name='category',
            name='preview',
            field=models.ImageField(blank=True, upload_to=product.models.category_preview_directory_pass),
        ),
    ]
