# Generated by Django 3.0.1 on 2020-01-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_design_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='discount',
        ),
    ]
