# Generated by Django 3.0.1 on 2020-01-04 09:06

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_design_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='preview',
            field=models.ImageField(upload_to=product.models.design_preview_directory_path),
        ),
        migrations.AlterField(
            model_name='design',
            name='vector',
            field=models.ImageField(blank=True, upload_to=product.models.design_vector_directory_path),
        ),
    ]
