# Generated by Django 3.0.1 on 2020-01-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_template_file_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_file',
            name='format',
        ),
        migrations.AlterField(
            model_name='template_file',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
