# Generated by Django 3.0.1 on 2020-01-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20200104_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Template_File',
            new_name='TemplateFile',
        ),
    ]
