# Generated by Django 3.0.1 on 2020-01-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20200105_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='min_time',
            new_name='max_time',
        ),
    ]
