# Generated by Django 3.0.1 on 2020-01-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20200105_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selling_Option',
            new_name='SellingOption',
        ),
        migrations.AddField(
            model_name='design',
            name='base',
            field=models.BooleanField(default=False),
        ),
    ]
