# Generated by Django 3.0.1 on 2020-01-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20200105_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_category', to='product.Classification'),
        ),
    ]
