# Generated by Django 3.0.1 on 2020-01-12 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20200111_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='design_feature',
        ),
        migrations.AddField(
            model_name='product',
            name='design_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='design_film',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='design_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='design_gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classification',
            name='title',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='brief_intro',
            field=models.TextField(blank=True, max_length=777, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.TextField(blank=True, max_length=2020, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
    ]
