# Generated by Django 3.0.1 on 2020-01-13 14:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_uploadfile'),
        ('product', '0032_category_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('cost', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(1000000)])),
                ('description', models.CharField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.AlterModelOptions(
            name='ready',
            options={'ordering': ['-duration']},
        ),
        migrations.AlterModelOptions(
            name='sellingoption',
            options={'ordering': ['size', 'ready', 'count', 'side']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['-len']},
        ),
        migrations.CreateModel(
            name='ProductServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_all_service', to='product.Product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_product', to='product.Service')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_all_services', to='order.Order')),
                ('product_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_in_order', to='product.ProductServices')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='services',
            field=models.ManyToManyField(db_index=True, related_name='all_service', through='product.ProductServices', to='product.Service'),
        ),
    ]
