# Generated by Django 3.0.1 on 2020-01-14 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20200113_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cut',
        ),
        migrations.AddField(
            model_name='size',
            name='cut_margin',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='size',
            name='safe_margin',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
