# Generated by Django 3.0.1 on 2020-01-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_service_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='classification',
            options={'verbose_name': 'کلاس بندی', 'verbose_name_plural': 'کلاس بندی'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ ها', 'verbose_name_plural': 'رنگ ها'},
        ),
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name': 'طراحی', 'verbose_name_plural': 'طراحی'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیفات', 'verbose_name_plural': 'تخفیفات'},
        ),
        migrations.AlterModelOptions(
            name='orderproductservices',
            options={'verbose_name': 'خدمات در سفارش', 'verbose_name_plural': 'خدمات در سفارش'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productservices',
            options={'verbose_name': 'خدمات در محصول', 'verbose_name_plural': 'خدمات در محصول'},
        ),
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name': 'کیفیت چاپ', 'verbose_name_plural': 'کیفیت چاپ'},
        ),
        migrations.AlterModelOptions(
            name='ready',
            options={'ordering': ['-duration'], 'verbose_name': 'فرم تحویل', 'verbose_name_plural': 'فرم تحویل'},
        ),
        migrations.AlterModelOptions(
            name='sellingoption',
            options={'ordering': ['size', 'ready', 'count', '-side'], 'verbose_name': 'گزینه های محصول', 'verbose_name_plural': 'گزینه های محصول'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'خدمات اختصاصی', 'verbose_name_plural': 'خدمات اختصاصی'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['-len'], 'verbose_name': 'سایز', 'verbose_name_plural': 'سایز'},
        ),
        migrations.AlterModelOptions(
            name='templatefile',
            options={'verbose_name': 'فایل راهنما', 'verbose_name_plural': 'فایل راهنما'},
        ),
    ]
