# Generated by Django 3.0.1 on 2020-01-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20200116_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['len'], 'verbose_name': 'سایز', 'verbose_name_plural': 'سایز'},
        ),
        migrations.RemoveField(
            model_name='sellingoption',
            name='sale_price',
        ),
    ]
