# Generated by Django 3.0.1 on 2020-01-20 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20200120_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingoption',
            name='auto_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-999999), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
