# Generated by Django 3.0.1 on 2020-01-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20200120_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['price'], 'verbose_name': 'طراحی', 'verbose_name_plural': 'طراحی'},
        ),
        migrations.AlterField(
            model_name='product',
            name='design_base',
            field=models.BooleanField(default=True),
        ),
    ]
