# Generated by Django 5.2.1 on 2025-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=78, verbose_name='Company Name')),
                ('phone_number', models.CharField(blank=True, max_length=23, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_media', models.JSONField(blank=True, default=dict, null=True, verbose_name='Social Media')),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('wellcome_massage', models.TextField(blank=True, max_length=300, null=True, verbose_name='Wellcome Massage')),
                ('login_massage', models.TextField(blank=True, max_length=300, null=True, verbose_name='Login Massage')),
                ('rules_page_check', models.BooleanField(default=False, verbose_name='Rules Page Check')),
                ('about_me', models.TextField(blank=True, max_length=1092, null=True, verbose_name='About Me')),
                ('google_code', models.CharField(blank=True, max_length=23, null=True, verbose_name='Google Code')),
                ('google_code_type', models.CharField(blank=True, choices=[('UA', 'Ua'), ('GA$', 'Ga4')], default='UA', max_length=3, null=True, verbose_name='Google Code Type')),
                ('robots_txt', models.TextField(blank=True, max_length=1092, null=True, verbose_name='robots.txt')),
                ('redirect_list', models.JSONField(blank=True, default=dict, null=True, verbose_name='Redirect List')),
            ],
            options={
                'verbose_name': 'Main Page',
                'verbose_name_plural': 'Main Pages',
            },
        ),
    ]
