# Generated by Django 5.2.1 on 2025-06-02 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='metadate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.metadata', verbose_name='main_page'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='rules_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_config', to='landing.landing', verbose_name='Rules Page'),
        ),
    ]
