# Generated by Django 3.0.1 on 2019-12-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamGraphicWeb', '0002_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(default='q', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='q', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='1', max_length=9, primary_key=True, serialize=False, verbose_name='Mobile Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='reg_data',
            field=models.DateField(auto_now=True, verbose_name='Register Data'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Profile',
            field=models.ImageField(blank=True, default=0, upload_to='', verbose_name='Profile Image'),
        ),
    ]
