# Generated by Django 3.0.1 on 2019-12-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamGraphicWeb', '0004_auto_20191230_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Mobile Number'),
        ),
    ]
