# Generated by Django 3.0.1 on 2019-12-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamGraphicWeb', '0005_auto_20191230_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reg_data',
            new_name='reg_date',
        ),
        migrations.AddField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
