# Generated by Django 3.0.1 on 2019-12-30 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TeamGraphicWeb', '0006_auto_20191230_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='user',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 11, 3, 11, 485567, tzinfo=utc)),
        ),
    ]
