# Generated by Django 3.0.1 on 2019-12-30 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TeamGraphicWeb', '0007_auto_20191230_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
