# Generated by Django 5.2 on 2025-05-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiCategory',
        ),
        migrations.DeleteModel(
            name='ApiItem',
        ),
    ]
