# Generated by Django 5.2 on 2025-05-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicategory',
            options={'ordering': ['sort_number'], 'verbose_name': 'API Category', 'verbose_name_plural': 'API Categories'},
        ),
        migrations.AlterModelOptions(
            name='apiitem',
            options={'ordering': ['sort_number'], 'verbose_name': 'API Item', 'verbose_name_plural': 'API Items'},
        ),
        migrations.AddField(
            model_name='apicategory',
            name='sort_number',
            field=models.IntegerField(default=0),
        ),
    ]
