# Generated by Django 5.2 on 2025-05-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_color_options_alter_design_options_and_more'),
        ('users', '0008_employeelevel_introduction_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('status_title', models.CharField(max_length=23, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_data', models.DateField(blank=True, null=True)),
                ('cart_status', models.CharField(max_length=23)),
                ('cart_price', models.IntegerField(default=0)),
                ('delivery_price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cart_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_title', models.CharField(max_length=23)),
                ('fields', models.JSONField(default=dict)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('internal_id', models.IntegerField(blank=True, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('options', models.JSONField(default=dict)),
                ('options_price', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('delivery_method', models.CharField(blank=True, max_length=23, null=True)),
                ('reports', models.JSONField(default=dict)),
                ('notes', models.JSONField(default=dict)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_list', to='orders.cart')),
                ('delivery_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliver_order_list', to='users.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product')),
                ('sale_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submit_order_list', to='users.employee')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus')),
            ],
        ),
    ]
