# Generated by Django 5.2 on 2025-05-26 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0008_employeelevel_introduction_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='sort_number',
            field=models.IntegerField(default=0, verbose_name='Sort Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_title',
            field=models.CharField(max_length=23, verbose_name='Order Title'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status_title',
            field=models.CharField(max_length=23, unique=True, verbose_name='Status Title'),
        ),
        migrations.CreateModel(
            name='OrderStatusAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_statuses', to='users.employee')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employees', to='orders.orderstatus', verbose_name='Order Status')),
            ],
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='employee_access',
            field=models.ManyToManyField(through='orders.OrderStatusAccess', through_fields=('order_status', 'employee'), to='users.employee'),
        ),
    ]
