# Generated by Django 5.2 on 2025-05-26 18:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderstatus_sort_order_and_more'),
        ('products', '0004_alter_design_category'),
        ('users', '0010_alter_introduction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['-sort_number'], 'verbose_name': 'Order Status', 'verbose_name_plural': 'Order Statuses'},
        ),
        migrations.AlterModelOptions(
            name='orderstatusaccess',
            options={'verbose_name': 'Order Status Access', 'verbose_name_plural': 'Order Status Accesses'},
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='status_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_employee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_title',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('جدید', 'New'), ('پرداخت شده', 'Payment'), ('تأیید شده', 'Confirm'), ('نهایی شده', 'End')], default='جدید', max_length=10, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Delivery Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='status_in_orders', to='orders.orderstatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default=0, max_length=23, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_data',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='options_price',
            field=models.IntegerField(default=0, verbose_name='Options Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_in_orders', to='products.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submit_order_list', to='users.employee', verbose_name='Sale Employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='employee_access',
            field=models.ManyToManyField(through='orders.OrderStatusAccess', through_fields=('order_status', 'employee'), to='users.employee', verbose_name='Employee Access'),
        ),
        migrations.AlterField(
            model_name='orderstatusaccess',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_order_statuses', to='users.employee'),
        ),
    ]
