# Generated by Django 5.2 on 2025-05-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_alter_deliverycategory_sort_number_and_more'),
        ('orders', '0003_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_receipt_order', to='deliveries.deliveryreceipt', verbose_name='Delivery Receipt'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='class_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Delivery Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='options_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Options Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='sort_number',
            field=models.SmallIntegerField(default=0, verbose_name='Sort Number'),
        ),
    ]
