# Generated by Django 5.2 on 2025-05-27 10:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_receipt_alter_cart_total_price_and_more'),
        ('users', '0013_remove_userprofile_company_remove_userprofile_credit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='class_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='classify_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Classify ID'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='order_status_role',
            field=models.CharField(choices=[('CRT', 'Cart'), ('NEW', 'New'), ('RED', 'Ready'), ('DLI', 'Delivered'), ('CAN', 'Cancel'), ('CUS', 'Custom')], default='CUS', max_length=3, verbose_name='Order Status Role'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='style',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('سبد خرید', 'Cart'), ('پرداخت شده', 'Payment'), ('تأیید مالی', 'Confirm'), ('نهایی شده', 'End')], default='سبد خرید', max_length=10, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Internal ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=23, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='title',
            field=models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.CreateModel(
            name='ExclusiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=73, validators=[django.core.validators.MinLengthValidator(3)])),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request Date')),
                ('status', models.CharField(choices=[('جدید', 'New'), ('در انتظار پاسخ', 'Response'), ('در انتظار تایید کاربر', 'Order'), ('سفارش داده شده', 'Submit'), ('بسته شده', 'Closed')], default='جدید', max_length=23)),
                ('content', models.JSONField(default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exclusive_order_request', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exclusive_order_response', to='users.employee')),
            ],
        ),
    ]
