# Generated by Django 5.2 on 2025-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_class_id_cart_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusiveorder',
            name='description',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
