# Generated by Django 5.2 on 2025-05-30 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_exclusiveorder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alt',
            field=models.CharField(default=0, max_length=73, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
    ]
