# Generated by Django 5.2.1 on 2025-06-02 07:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('number', models.PositiveIntegerField(default=0)),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
            ],
            options={
                'verbose_name': 'Introduce',
                'verbose_name_plural': 'Introduces',
                'ordering': ['-sort_number'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('sort_number', models.SmallIntegerField(default=0, verbose_name='Sort Number')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Phone Number')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='National ID')),
                ('public_key', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Public Key')),
                ('private_key', models.CharField(max_length=20, verbose_name='Private Key')),
                ('accounting_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Accounting ID')),
                ('accounting_name', models.CharField(blank=True, max_length=73, null=True, verbose_name='Accounting Name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_all_users', to='user.role')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('U', 'تعیین نشده')], default='U', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=25, null=True)),
                ('total_order', models.PositiveIntegerField(default=0, verbose_name='Total Order')),
                ('last_order_price', models.PositiveIntegerField(default=0, verbose_name='Last Order Price')),
                ('last_order_date', models.DateField(blank=True, null=True, verbose_name='Last Order Date')),
                ('total_product_buy', models.PositiveIntegerField(default=0, verbose_name='Total Product Buy')),
                ('total_option_buy', models.PositiveIntegerField(default=0, verbose_name='Total Option Buy')),
                ('introduce_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='introduce_all_users', to='user.introduction', verbose_name='Introduction from')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user'],
            },
        ),
    ]
