# Generated by Django 5.2.1 on 2025-06-02 10:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Is Employee'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23, validators=[django.core.validators.MinLengthValidator(3)])),
                ('state', models.CharField(blank=True, max_length=37, null=True)),
                ('city', models.CharField(blank=True, max_length=37, null=True)),
                ('content', models.TextField(max_length=300)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Postal Code')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Phone Number')),
                ('plate_number', models.CharField(max_length=10, verbose_name='Plate Number')),
                ('unit_number', models.CharField(max_length=10, verbose_name='Unit Number')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('submit_date', models.DateField(default=django.utils.timezone.now, verbose_name='Submit Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['is_default', '-submit_date'],
            },
        ),
    ]
