
TG_SIGNUP_INTEGRITY = 'کاربر با این شماره تماس وجود دارد!'
TG_SIGNIN_ERROR = 'اطلاعات وارد شده صحیح نمی باشد.'
TG_USER_NOT_FOUND_BY_ID = 'کاربر مورد نظر وجود ندارد.'
TG_USER_NOT_FOUND_BY_PHONE = 'کاربر با شماره تماس وارد شده وجود ندارد.'
TG_USER_CREATED = 'اشتراک کاربری شما ایجاد شد.'
TG_EXPECTED_PHONE_NUMBER = 'لطفا شماره تماس را به درستی وارد کنید.'
TG_EXPECTED_ID_NUMBER = 'لطفا عدد صحیح وارد کنید.'
TG_DATA_NOT_FOUND = 'اطلاعات یافت نشد!'
TG_DATA_EMPTY = 'اطلاعات خالی است!'
TG_DATA_CREATED = 'اطلاعات ذخیره شد.'
TG_PREVENT_DELETE_DEFAULT = 'آبجکت پیشفرض قابل حذف نیست!'
TG_PREVENT_DELETE_PROTECTED = 'آبجکت وابسته قابل حذف نیست!'
TG_DATA_DELETED = 'اطلاعات با موفقیت حذف شد!'
TG_PERMISSION_DENIED = 'اجازه دسترسی ندارید!'
TG_DATA_UPDATED = 'اطلاعات بروزرسانی شد!'
TG_DATA_WRONG = 'اطلاعات ارسالی غلط می باشد!'
